apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullName" . }}
  labels:
    app: {{ include "fullName" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fullName" . }}
  template:
    metadata:
      labels:
        app: {{ include "fullName" . }}
    spec:
      containers:
        - name: {{ include "fullName" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
