{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullName" . }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ printf "%s.apps.%s" .Values.ingress.hostname .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "fullName" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ printf "%s.apps.%s" .Values.ingress.hostname .Values.ingress.domain }}
      secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
{{- end }}
