apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullName" . }}
  labels:
    app: {{ include "fullName" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "fullName" . }}
