# Deployment type: "deployment" or "statefulset"
deploymentType: "statefulset"

# Basic configuration
nameOverride: ""
fullnameOverride: ""
replicaCount: 1

# Image configuration
image:
  registry: registry.web.boeing.com
  repository: missionaccelerator/devsecops/registry/keycloak
  tag: "IMAGE_VERSION"
  pullPolicy: IfNotPresent

# StatefulSet configuration
statefulset:
  serviceName: keycloak-headless

# Environment configuration
env:
  secretRefs:
    - name: gitlab-registry
    - name: keycloak

# Secrets
secrets:
  gitlabRegistry:
    enabled: true
    name: gitlab-registry
    type: kubernetes.io/dockerconfigjson
    data:
      .dockerconfigjson: ""
  
  keycloak:
    enabled: true
    name: keycloak
    type: Opaque
    data:
      KEYCLOAK_ADMIN: YWRtaW4=
      KEYCLOAK_ADMIN_PASSWORD: YWRtaW4xMjM=

# Storage configuration
persistence:
  enabled: true
  home:
    name: home
    size: 1Gi
    storageClass: "standard"
    mountPath: /opt/home
  data:
    name: keycloak-data
    size: 1Gi
    storageClass: "standard"
    mountPath: /opt/data

# Resources
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 750m
    memory: 1536Mi

# Service configuration
service:
  type: ClusterIP
  port: 443
  targetPort: 8443
  headlessEnabled: true

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: keycloak.local
      paths:
        - path: /
          pathType: Prefix
  tls: []