replicaCount: 1

namespace: laborlossmetrics

image:
  repository: your-registry/partsui
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  # nodePort: 31000   # uncomment or set if you need a fixed port

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "0.5"
    memory: "1Gi"
