{{- if .Values.secrets.gitlabRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.gitlabRegistry.name }}
  namespace: {{ include "keycloak.namespace" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: {{ .Values.secrets.gitlabRegistry.type }}
data:
  {{- with .Values.secrets.gitlabRegistry.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- end }}
{{- if .Values.secrets.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.keycloak.name }}
  namespace: {{ include "keycloak.namespace" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: {{ .Values.secrets.keycloak.type }}
data:
  {{- with .Values.secrets.keycloak.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}