{{- if .Values.secrets.gitlabRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.gitlabRegistry.name }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: {{ .Values.secrets.gitlabRegistry.type }}
data:
  {{- toYaml .Values.secrets.gitlabRegistry.data | nindent 2 }}
---
{{- end }}
{{- if .Values.secrets.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.keycloak.name }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: {{ .Values.secrets.keycloak.type }}
data:
  {{- toYaml .Values.secrets.keycloak.data | nindent 2 }}
{{- end }}