apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.serviceName" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
---
{{- if and .Values.service.headlessEnabled (eq .Values.deploymentType "statefulset") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.headlessServiceName" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
{{- end }}