{{- if eq .Values.deploymentType "statefulset" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "keycloak.headlessServiceName" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: keycloak
          image: {{ include "keycloak.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          envFrom:
            {{- range .Values.env.secretRefs }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: {{ .Values.persistence.home.name }}
              mountPath: {{ .Values.persistence.home.mountPath }}
            - name: {{ .Values.persistence.data.name }}
              mountPath: {{ .Values.persistence.data.mountPath }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.persistence.home.name }}
        labels:
          {{- include "keycloak.labels" . | nindent 10 }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.persistence.home.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.home.size }}
    - metadata:
        name: {{ .Values.persistence.data.name }}
        labels:
          {{- include "keycloak.labels" . | nindent 10 }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.persistence.data.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.data.size }}
  {{- end }}
{{- end }}